
**Question 1**

What's the version of NumPy that you installed?

In [1]:
import numpy as np
import pandas as pd
np.__version__

'1.21.5'

**Getting the data**

For this homework, we'll use the Car price dataset. Download it from here.

You can do it with wget:

wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv

Or just open it with your browser and click "Save as...".

Now read it with Pandas.

In [2]:
%%bash
# Download the Car price dataset only if it is not already downloaded
# wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv

In [3]:
df_cars = pd.read_csv('./data.csv')
df_cars.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

**Question 2**

How many records are in the dataset?

Here you need to specify the number of rows.
-   16
-   6572
-   11914
-   18990

In [4]:
print(f'Number of records in the dataset: {df_cars.shape[0]}')

Number of records in the dataset: 11914


In [5]:
df_cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Make               11914 non-null  object 
 1   Model              11914 non-null  object 
 2   Year               11914 non-null  int64  
 3   Engine Fuel Type   11911 non-null  object 
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  object 
 7   Driven_Wheels      11914 non-null  object 
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object 
 10  Vehicle Size       11914 non-null  object 
 11  Vehicle Style      11914 non-null  object 
 12  highway MPG        11914 non-null  int64  
 13  city mpg           11914 non-null  int64  
 14  Popularity         11914 non-null  int64  
 15  MSRP               11914 non-null  int64  
dtypes: float64(3), int64(5

**Question 3**

Who are the most frequent car manufacturers (top-3) according to the dataset?
-   Chevrolet, Volkswagen, Toyota
-   Chevrolet, Ford, Toyota
-   Ford, Volkswagen, Toyota
-   Chevrolet, Ford, Volkswagen

Note: You should rely on "Make" column in this question.

In [6]:
df_cars.Make.nunique()

48

In [7]:
df_cars.Make.value_counts()[:3]

Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

**Question 4**

What's the number of unique Audi car models in the dataset?
-   3
-   16
-   26
-   34

In [8]:
df_cars.query("Make=='Audi'").Model.nunique()

34

**Question 5**

How many columns in the dataset have missing values?
-   5
-   6
-   7
-   8

In [9]:
print(f'Number of columns with missing values: {df_cars.isna().any().sum()}')
df_cars.isna().any()

Number of columns with missing values: 5


Make                 False
Model                False
Year                 False
Engine Fuel Type      True
Engine HP             True
Engine Cylinders      True
Transmission Type    False
Driven_Wheels        False
Number of Doors       True
Market Category       True
Vehicle Size         False
Vehicle Style        False
highway MPG          False
city mpg             False
Popularity           False
MSRP                 False
dtype: bool

**Question 6**

1.  Find the median value of "Engine Cylinders" column in the dataset.
2.  Next, calculate the most frequent value of the same "Engine Cylinders".
3.  Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
4.  Now, calculate the median value of "Engine Cylinders" once again.

Has it changed?

    Hint: refer to existing mode and median functions to complete the task.
-   Yes
-   No

In [10]:
print(f"Median number of cylinders before imputing: {df_cars['Engine Cylinders'].median()}")

Median number of cylinders before imputing: 6.0


In [11]:
# Returns frequency counts for each value in decreasing order
# Included the count of missing values too

print(df_cars['Engine Cylinders'].value_counts(dropna=False))

4.0     4752
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
NaN       30
3.0       30
16.0       3
Name: Engine Cylinders, dtype: int64


In [12]:
# Method 'value_counts' returns a Pandas series - the value with maximum count is extracted

frequent = df_cars['Engine Cylinders'].value_counts().idxmax()
print(f'Most frequent value is: {frequent}')

Most frequent value is: 4.0


In [13]:
# Alternatively, the 'mode' function can be used - but it also returns a series with multiple most frequent
# values, if present. The first one is chosen.

frequent = df_cars['Engine Cylinders'].mode().iloc[0]
print(f'Most frequent value is: {frequent}')

Most frequent value is: 4.0


In [14]:
cylinders_imputed = df_cars['Engine Cylinders'].fillna(value=frequent)
print(cylinders_imputed.value_counts(dropna=False))

4.0     4782
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
3.0       30
16.0       3
Name: Engine Cylinders, dtype: int64


In [15]:
print(f"Median number of cylinders after imputing: {cylinders_imputed.median()}")

Median number of cylinders after imputing: 6.0


**Question 7**

1.  Select all the "Lotus" cars from the dataset.
2.  Select only columns "Engine HP", "Engine Cylinders".
3.  Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).
4.  Get the underlying NumPy array. Let's call it X.
5.  Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
6.  Invert XTX.
7.  Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].
8.  Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
9.  What's the value of the first element of w?

    Note: You just implemented linear regression. We'll talk about it in the next lesson.
-   -0.0723
-   4.5949
-   31.6537
-   63.5643

In [16]:
df_lotus = df_cars.query("Make == 'Lotus'")[['Engine HP', 'Engine Cylinders']].drop_duplicates()
df_lotus

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [17]:
X = np.array(df_lotus)
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [18]:
XTX = X.T @ X
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [19]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [20]:
# Verify that inverse computation is correct
np.ndarray.round(XTX @ XTX_inv, 4)

array([[1., 0.],
       [0., 1.]])

In [21]:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])
y

array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800])

In [22]:
w = (XTX_inv @ X.T) @ y
w

array([  4.59494481, -63.56432501])

In [23]:
print(f'Value of the first element of w is: {round(w[0],4)}')

Value of the first element of w is: 4.5949
